"""Generate src/data/voices.ts from each model's own voice manifest.

The catalog used to be hand-written, which is how it drifted: it listed voice
ids like `vieneu_vinh` that no daemon knows, and four Kokoro-82M English voices
after the model was replaced. Read the manifests directly -- loading the models
just to list voices costs minutes of GPU time for data that is plain JSON.

  python3 scripts/gen_voices.py
"""
import json
import os
import subprocess
import sys

# Repo root derived from this file, so the script works wherever it is checked
# out. Override with VIENEU_PYTHON when VieNeu lives in its own venv.
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY = os.environ.get('VIENEU_PYTHON', sys.executable)

SAMPLES = {
    'vieneu': 'Đến cuối thế kỷ 19, ngành đánh bắt cá được thương mại hóa mạnh mẽ.',
    'kokoro': 'Giữa một buổi chiều yên tĩnh, cô ấy kể lại câu chuyện bằng một giọng nói ấm áp.',
    'mms': 'E2Aubooks chuyển đổi sách nói với giọng đọc tiếng Việt tự nhiên.',
}

LABEL = {'vieneu': 'VieNeu-TTS v3 Turbo', 'kokoro': 'Kokoro Vietnamese',
         'mms': 'Meta MMS Vietnamese'}
REGION = {'Bắc': 'Miền Bắc', 'Trung': 'Miền Trung', 'Nam': 'Miền Nam'}


def vieneu_voices():
    """The SDK ships voices_v3_turbo.json; read it instead of importing the model."""
    path = subprocess.run(
        [PY, '-c', 'import vieneu,os;print(os.path.join(os.path.dirname(vieneu.__file__),'
                   '"assets","voices_v3_turbo.json"))'],
        capture_output=True, text=True).stdout.strip()
    data = json.load(open(path, encoding='utf-8'))
    # The SDK's own default first -- it is what the model card presents and what
    # reads as neutral narration. `featured` is editorial ranking, not a
    # default, and ordering by it put "Adam bựa" in front of every book.
    default = data.get('default_voice', '')
    presets = sorted(data['presets'].items(),
                     key=lambda kv: (kv[0] != default, kv[1].get('featured', 99)))
    return [{'name': k, 'voice_id': k.lower().replace(' ', '_'),
             'gender': v.get('gender', ''), 'region': v.get('region', ''),
             'style': v.get('style', ''), 'description': v.get('description', '')}
            for k, v in presets]


def kokoro_voices():
    path = os.path.join(ROOT, 'models/kokoro-vietnamese/voices.json')
    meta = json.load(open(path, encoding='utf-8'))
    return [{'name': m['label'], 'voice_id': vid} for vid, m in sorted(
        meta.items(), key=lambda kv: kv[1]['label'])]


def mms_voices():
    # The VITS model has one speaker per gender and no speaker list of its own.
    return [{'name': 'Nam', 'voice_id': 'male', 'gender': 'male'},
            {'name': 'Nữ', 'voice_id': 'female', 'gender': 'female'}]


def gender_of(g):
    return 'female' if (g or '').lower() in ('female', 'f', 'nữ') else 'male'


def q(s):
    """Quote for TypeScript. Voice names carry diacritics, quotes and the odd
    apostrophe, so hand-built string literals break the file."""
    return json.dumps(str(s), ensure_ascii=False)


def main():
    lines = [
        "import { AudiobookVoice } from '../types/ebook';",
        '',
        "// Generated by scripts/gen_voices.py from each model's own voice manifest.",
        '// Edit the generator, not this file.',
        '',
        'export const DEFAULT_VOICES: AudiobookVoice[] = [',
        '',
    ]
    total = 0
    for engine, loader in (('vieneu', vieneu_voices),
                           ('kokoro', kokoro_voices),
                           ('mms', mms_voices)):
        try:
            voices = loader()
        except Exception as ex:
            print(f'{engine}: {type(ex).__name__}: {ex}')
            continue
        lines.append(f'  // ---- {LABEL[engine]} ----')
        for v in voices:
            desc = v.get('description') or v['name']
            lines.append(
                "    {\n"
                f"    id: {q(engine + '_' + v['voice_id'])},\n"
                f"    name: {q(v['name'])},\n"
                f"    engine: {q(engine)},\n"
                f"    engineLabel: {q(LABEL[engine])},\n"
                "    lang: 'vi-VN',\n"
                "    languageLabel: 'Tiếng Việt',\n"
                f"    gender: {q(gender_of(v.get('gender')))},\n"
                f"    accent: {q(REGION.get(v.get('region', ''), 'Miền Bắc'))},\n"
                f"    styleDescription: {q(desc)},\n"
                f"    tag: {q(v.get('style') or LABEL[engine])},\n"
                "    isNeural: true,\n"
                "    hardwareTarget: 'CPU / GPU',\n"
                f"    sampleText: {q(SAMPLES[engine])},\n"
                '  },')
            total += 1
        lines.append('')
    lines.append('];')

    dest = os.path.join(ROOT, 'src/data/voices.ts')
    with open(dest, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'wrote {total} voices -> {dest}')


main()